---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:

    - name: Remove conflicting containerd packages
      apt:
        name:
          - containerd
          - containerd.io
        state: absent
        purge: yes
        autoremove: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      # Change 'focal' if your Ubuntu version is different (e.g., 'jammy' for 22.04)

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE and containerd.io
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if a container named 'insure-me-app' exists
      shell: docker ps -a --filter "name=^/insure-me-app$" --format "{{'{{'}}.ID{{'}}'}}"
      register: container_id_result
      changed_when: false
      ignore_errors: true

    - name: Restart existing container if it exists
      shell: docker restart insure-me-app
      when: container_id_result is defined and container_id_result.stdout != ""
      ignore_errors: true

    - name: Run new container if not already running
      docker_container:
        name: insure-me-app
        image: sachinbacha/insure-me:latest
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
      when: container_id_result is not defined or container_id_result.stdout == ""

