- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name: Ensure Docker service is started and enabled
      service:
          name: docker
          state: started
          enabled: yes

  - name: Deploy Docker Container
    docker_container:
      name: insure-me-app
      image: sachinbacha/Insure-me:latest
      state: started
      restart_policy: always
      ports:
        - "8084:8080"
