- name: Download and Run Selenium JAR
  hosts: all
  become: true
  tasks:
    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        state: present
        
    - name: Clone GitHub Repo
      git:
        repo: 'https://github.com/bachasachin0/star-agile-insurance-project'
        dest: /home/devops/test-app
        version: master 

    - name: Run Selenium test JAR
      shell: java -jar /home/devops/test-app/selenium-insure-me-runnable.jar
