---
- name: Run Selenium tests on test machine
  hosts: test_machine    # make sure your inventory defines this host/group
  become: yes            # if needed to run as sudo
  tasks:
    - name: Ensure Java and Maven wrapper are available (optional)
      package:
        name: openjdk-11-jdk
        state: present
      become: yes

    - name: Run Selenium tests with Maven wrapper
      shell: ./mvnw test
      args:
        chdir: /home/devops/test-app
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64  # Adjust path if needed
      register: test_result
      ignore_errors: yes

    - name: Print test output
      debug:
        var: test_result.stdout_lines

    - name: Fail if tests failed
      fail:
        msg: "Selenium tests failed!"
      when: test_result.rc != 0
