- name: Download and Run Selenium JAR
  hosts: all
  become: true
  tasks:

    - name: Remove old versions of Google Chrome if present
      apt:
        name: google-chrome-stable
        state: absent
        purge: yes
      ignore_errors: true

    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install unzip and jq
      apt:
        name:
          - unzip
          - jq
        state: present

    - name: Download and install latest Google Chrome
      shell: |
        wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt install -y /tmp/google-chrome.deb
      args:
        creates: /usr/bin/google-chrome

    - name: Get installed Chrome version
      shell: google-chrome --version | grep -oP '\d+\.\d+\.\d+'
      register: chrome_version

    - name: Fetch latest ChromeDriver version
      shell: |
        curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json \
        | jq -r '.channels.Stable.version'
      register: chromedriver_version

    - name: Download and install ChromeDriver
      shell: |
        wget -q -O /tmp/chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{ chromedriver_version.stdout }}/linux64/chromedriver-linux64.zip"
        unzip -o /tmp/chromedriver.zip -d /tmp/chromedriver
        mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        chmod +x /usr/local/bin/chromedriver
      args:
        creates: /usr/local/bin/chromedriver

    - name: Verify ChromeDriver
      shell: chromedriver --version

    - name: Clone GitHub Repo
      git:
        repo: 'https://github.com/bachasachin0/star-agile-insurance-project'
        dest: /home/devops/test-app
        version: master

    - name: Run Selenium test JAR
      shell: java -jar /home/devops/test-app/selenium-insure-me-runnable.jar
      args:
        chdir: /home/devops/test-app

    # ---------- Cleanup Tasks ----------
    - name: Remove downloaded Chrome .deb and ChromeDriver zip
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/google-chrome.deb
        - /tmp/chromedriver.zip

    - name: Remove extracted ChromeDriver temp dir
      file:
        path: /tmp/chromedriver
        state: absent
        recurse: yes
