- name: Download and Run Selenium JAR
  hosts: all
  become: true
  tasks:
    - name: Install Java (OpenJDK 11)
      package:
        name: java-11-openjdk
        state: present

    - name: Clone GitHub Repo
      git:
        repo: 'https://github.com/your-username/your-repo.git'
        dest: /home/devops/test-app
        version: master 

    - name: Run Selenium test JAR
      shell: java -jar /home/devops/test-app/selenium-insure-me-runnable.jar
