- name: Setup environment and run Selenium test JAR
  hosts: all
  become: true
  tasks:

    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Remove old ChromeDriver if exists
      file:
        path: /usr/local/bin/chromedriver
        state: absent
      ignore_errors: yes

    - name: Get installed Chrome major version
      shell: google-chrome --version | grep -oP '\d+' | head -1
      register: chrome_major_version
      changed_when: false

    - name: Download matching ChromeDriver version and install
      shell: |
        CHROME_VERSION={{ chrome_major_version.stdout }}
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -o /tmp/chromedriver.zip -d /tmp/chromedriver
        mv /tmp/chromedriver/chromedriver /usr/local/bin/chromedriver
        chmod +x /usr/local/bin/chromedriver
      args:
        creates: /usr/local/bin/chromedriver

    - name: Clone GitHub Repo
      git:
        repo: 'https://github.com/bachasachin0/star-agile-insurance-project'
        dest: /home/devops/test-app
        version: master
        force: yes

    - name: Run Selenium test JAR
      shell: java -jar /home/devops/test-app/selenium-insure-me-runnable.jar
      args:
        chdir: /home/devops/test-app

    - name: Clean up ChromeDriver zip file
      file:
        path: /tmp/chromedriver.zip
        state: absent
      ignore_errors: yes
