- name: Setup environment and run Selenium test JAR
  hosts: all
  become: true
  tasks:

    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Remove existing Google Chrome if present
      apt:
        name: google-chrome-stable
        state: absent
      ignore_errors: yes

    - name: Download Chrome 124 .deb package
      get_url:
        url: https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.119-1_amd64.deb
        dest: /tmp/google-chrome.deb

    - name: Install Chrome 124
      apt:
        deb: /tmp/google-chrome.deb

    - name: Remove existing ChromeDriver
      file:
        path: /usr/local/bin/chromedriver
        state: absent
      ignore_errors: yes

    - name: Download ChromeDriver 124
      get_url:
        url: https://chromedriver.storage.googleapis.com/124.0.6367.91/chromedriver_linux64.zip
        dest: /tmp/chromedriver.zip

    - name: Unzip ChromeDriver
      unarchive:
        src: /tmp/chromedriver.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
      notify: Move ChromeDriver

    - name: Clone Selenium Test Repository
      git:
        repo: 'https://github.com/bachasachin0/star-agile-insurance-project'
        dest: /home/devops/test-app
        version: master
        force: yes

    - name: Run Selenium test JAR
      shell: java -jar selenium-insure-me-runnable.jar
      args:
        chdir: /home/devops/test-app
      register: selenium_run
      ignore_errors: yes

    - name: Show Selenium test output
      debug:
        var: selenium_run.stdout_lines

    - name: Fail if Selenium test JAR failed
      fail:
        msg: "Selenium test JAR execution failed!"
      when: selenium_run.rc != 0

  handlers:
    - name: Move ChromeDriver
      command: mv /usr/local/bin/chromedriver /usr/local/bin/chromedriver
